const express = require('express');
const OpenAIController = require("../openAI-gateway/OpenAIController");
const ChatController = require("../chat-module/ChatController");
const openaiRouter = express.Router();
const openaiController = new OpenAIController();
const chatController = new ChatController();
const processPromptHandler = openaiController.processPrompt.bind(openaiController);
const prompthandler = chatController.processInput.bind(chatController);
openaiRouter.post("/processPrompt", processPromptHandler);
openaiRouter.post("/prompt", prompthandler);
module.exports = openaiRouter;